name: 'Chrome extension webstore publish'
description: 'Publish your chrome extension to the chrome webstore using the delgated service account'
inputs:
  service-account-json:
    description: 'Service account json'
    required: true
  impersonated-user-email:
    description: 'Email of the Impersonated user in the organization'
    required: true
  chrome-extension-id:
    description: "Chrome extension id"
    required: true
  path:
    description: 'Path of the extension'
    required: true
  print-token:
    description: 'sample'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'